### ISSUE TITLE
AttributeError: module 'tensorflow_core.contrib' has no attribute 'lite'

### ISSUE THREAD

**Issue by rokopi-byte** [svpino/tensorflow-object-detection-sagemaker#1]
Hi,
I'm trying to train a detection network using sagemaker and found your great repo! 
However using tensorflow 1.15.0 I get the error (line 111 in train):
AttributeError: module 'tensorflow_core.contrib' has no attribute 'lite'
Because tensorflow lite has been moved from contrib to core since release 1.13 ..

**Comment by svpino** [comment]
Here is one thing you can try:

Notice that when building the Docker image, there's an ARCHITECTURE argument. Here you'll see "1.15.0-gpu". That specifies which version of TensorFlow to use (and whether to add GPU support).

Try and replace that with "1.13.1-gpu" when running the docker build. That should use the TensorFlow image with the proper version for you.
